name = "o6co"
type = "javascript"
workers_dev = true
compatibility_date = "2021-10-06"

# [vars]
# _=''
# TOKEN="1392892828:AAE_5FveSFZvwB-nInLKCq9Xt3ZIMAnSji0"

# [[kv-namespaces]]
# binding = "V"
# id = "0bbdbbfea669455cb1197c86efae78c9"

[[kv-namespaces]]
binding = "G"
id = "2d18c83a8de04b78898e0596d6ad321b"

[build]
command = "npm install && node build.js"

[build.upload]
format = "modules"
main = "./index.mjs"

